INSERT INTO product (name, description, price, type) VALUES ('Product 1', 'Description for product 1', 10.00,'clothing');
INSERT INTO product (name, description, price, type) VALUES ('Product 2', 'Description for product 2', 20.00,'electronics');
INSERT INTO product (name, description, price, type) VALUES ('Product 3', 'Description for product 3', 30.00,'clothing');
INSERT INTO product (name, description, price, type) VALUES ('Product 4', 'Description for product 4', 40.00,'electronics');
INSERT INTO product (name, description, price, type) VALUES ('Product 5', 'Description for product 5', 50.00,'clothing');
INSERT INTO product (name, description, price, type) VALUES ('Product 6', 'Description for product 6', 60.00,'electronics');
INSERT INTO product (name, description, price, type) VALUES ('Product 7', 'Description for product 7', 70.00,'electronics');
INSERT INTO product (name, description, price, type) VALUES ('Product 8', 'Description for product 8', 80.00,'clothing');
INSERT INTO product (name, description, price, type) VALUES ('Product 9', 'Description for product 9', 90.00,'electronics');
